version: "3"
services:
  postgres-rent-app:
    image: postgres:9.6
    restart: always
    container_name: postgres-rent-app
    environment:
      - POSTGRES_DB=PropertyRental
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
        - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 7879:5432